name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript
        run: yarn types:check

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier Check
        run: yarn prettier:check

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 15]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
